### PR TITLE
Since mesa version 21 was merged, the main branch should be checked out instead

### PR DESCRIPTION
**Pull request by crramirez**
Corrected the build instructions to download the lastest from mesa

Please add the label **hacktoberfest-accepted** if you accept this PR

### CODE REVIEW

**Comment by crramirez** [comment]
Solves #860

**Comment by hideyukn88** [comment]
We want to keep checking out 21 at this point, so if main branch gets updated, we don't get newer version accidentally. At our official build pipeline, the mesa source code is downloaded from our blob rather than cloning from GitHub, see below, so I guess we should check out by using 21 tag (since no more 21 branch)? what do you think?

https://github.com/microsoft/wslg/blob/d1c9e32ab196e6ec78c8b72ed1927e6a93db1638/azure-pipelines.yml#L43

**Comment by hideyukn88** [comment]
Or as https://github.com/microsoft/wslg/issues/860#issuecomment-1277650350 mentioned, we should mirror from original Gitlab repo.

**Comment by crramirez** [comment]
I think cloning from the tag will be a cleaner approach, because in GitLab eventually, the branch could disappear as well.

**Review by hideyukn88 — APPROVED** [review]

**Comment by crramirez** [comment]
@hideyukn88 Please add the label **hacktoberfest-accepted**

**Comment by hideyukn88** [comment]
@crramirez, is this what you need?

**Comment by crramirez** [comment]
Yes, thanks a lot. A bit of context:

https://hacktoberfest.com/participation/
image

**Comment by kingosticks** [comment]
Is it worth bumping to 21.3? It builds fine, I've been using it locally.

**Comment by WSLUser** [comment]
Latest version is 22.2, we really should be using that. It has more support for OpenGL and Vulkan if the right driver is installed.

**Comment by WSLUser** [comment]
I believe Mariner has a way for you to patch it similar to Clear Linux so you can change the package version. In fact Clear Linux tells you which specific deps you need for Mesa on their Mesa repo.

**Comment by tengzl33t** [comment]
`meson.build:1760:0: ERROR: Invalid version of dependency, need 'libdrm' ['>=2.4.109'] found '2.4.102'.`
Does not compile with Mesa 23.0.2l
Is Mesa 21.0.0 only supported version?

**Pull request merged**
